/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MBottomSheet: typeof import('./../libs/bottom-sheet/index.vue')['default']
    MButton: typeof import('./../libs/button/index.vue')['default']
    MCountDown: typeof import('./../libs/count-down/index.vue')['default']
    MDialog: typeof import('./../libs/dialog/index.vue')['default']
    MInfiniteScroll: typeof import('./../libs/infinite-scroll/index.vue')['default']
    MInput: typeof import('./../libs/input/index.vue')['default']
    MLazyImage: typeof import('./../libs/lazy-image/index.vue')['default']
    MNavbar: typeof import('./../libs/navbar/index.vue')['default']
    MPopover: typeof import('./../libs/popover/index.vue')['default']
    MSearch: typeof import('./../libs/search/index.vue')['default']
    MSvgIcon: typeof import('./../libs/svg-icon/index.vue')['default']
    MTransitionRouterView: typeof import('./../libs/transition-router-view/index.vue')['default']
    MWaterfall: typeof import('./../libs/waterfall/index.vue')['default']
  }
}
